DELETE FROM configuration WHERE configuration_key IN (
    'MODULE_PAYMENT_CUSTOMPAY_STATUS',
    'MODULE_PAYMENT_CUSTOMPAY_ZONE',
    'MODULE_PAYMENT_CUSTOMPAY_SORT_ORDER',
    'MODULE_PAYMENT_CUSTOMPAY_MERCHANT_ID',
    'MODULE_PAYMENT_CUSTOMPAY_API_KEY'
);

DROP TABLE IF EXISTS custompay_transactions;